# Generated by Django 5.0.2 on 2024-02-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modification_date', models.DateTimeField(auto_created=True, auto_now=True)),
                ('creation_date', models.DateTimeField(auto_created=True, auto_now=True)),
                ('url', models.CharField(max_length=500, unique=True)),
                ('status', models.BooleanField(blank=True, default=True, null=True)),
                ('short_url_pattern', models.CharField(max_length=200, unique=True)),
            ],
        ),
    ]
