# Generated by Django 5.0.2 on 2024-02-13 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_url', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
